server:
  port: 8080

spring:
  application:
    name: project
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.242.90.240:5432/anesthesia
    username: postgres
    password: medical310

stomp:
  server:
    url: ws://10.242.20.251:8080/ws
  topic: /data/sub/34:81:F4:75:20:70

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.medical.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

auth:
  enabled: false # set true to enforce token check
  shared-secret: "" # set to your token value (for simple shared-secret validation)
  header: Authorization
  bearer-prefix: "Bearer "
  ignore-paths: /error,/actuator/**

jwt:
  secret: Gvq3qwTLtylD/thEZikRdVUU2c5dv1GW+ZpC3BJDwOLU+8f22qPhFA5YXnRalpMz92HD3YiCCFjhyLM0mYGn8A==
  expiration: 18000000


